[Online]
URI = "zkevm-sequencer:6900"
StreamType = 1

[Offline]
Port = 6902
Filename = "./datastream.bin"
Version = 1
ChainID = 686868
UpgradeEtrogBatchNumber = 1642245

[StateDB]
User = "state_user"
Password = "state_password"
Name = "state_db"
Host = "43.134.127.80"
Port = "15432"
EnableLog = false
MaxConns = 200

[Executor]
URI = "43.134.127.80:50071"
MaxGRPCMessageSize = 100000000

[MerkleTree]
URI = "43.134.127.80:50061"
MaxThreads = 20
CacheFile = "merkle_tree_cache.json"

[Log]
Environment = "development"
Level = "debug"
Outputs = ["stdout"]
